### ISSUE TITLE
Документация!!! До 20.02

### ISSUE THREAD

**Issue by dan0nchik** [Natasha-rare/predprof#2]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/46318240/107927463-1c8a6780-6f88-11eb-977d-ebe6fc18f0ea.png">

**Полезные ссылки:**
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjJm7XZyOvuAhWv-yoKHVA2BIcQFjACegQIAxAC&url=http%3A%2F%2Ftehpis.ru%2Finfo%2Farticles%2Fprogrammdocs%2F&usg=AOvVaw2ljbMUs5VyBRWKEu8ySWcE

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjJm7XZyOvuAhWv-yoKHVA2BIcQFjADegQIBBAC&url=https%3A%2F%2Fhabr.com%2Fru%2Fpost%2F507414%2F&usg=AOvVaw1FOrCXsdZN9b0Utn-HbLSV

https://habr.com/ru/post/421549/

**Можно в принципе генератором попробовать воспользоваться**
https://ru.wikipedia.org/wiki/Документация_на_программное_обеспечение#Техническая_документация

**Примеры**
https://clevertap.com/blog/technical-documentation/

https://www.altexsoft.com/blog/business/technical-documentation-in-software-development-types-best-practices-and-tools/

**Comment by Natasha-rare** [comment]
Ну и сам пиши документацию


С уважением,
Наталья Автухович Отправлено из мобильной Почты Mail.Ru



Monday, 15 February 2021, 12:29 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by dan0nchik** [comment]
Я же ваху отметил, пусть он делает

**Comment by Natasha-rare** [comment]
А ок, без проблем


С уважением,
Наталья Автухович Отправлено из мобильной Почты Mail.Ru



Monday, 15 February 2021, 12:31 +0300 from notifications@github.com  <notifications@github.com>:
